In [3]:
pred_y=np.load("Predictions.npy")

In [2]:
import numpy as np

In [4]:
pred_y

array([[3.32223773e-02, 1.57029688e-01, 4.80267704e-01, ...,
        2.05025375e-02, 3.44476998e-02, 4.05013561e-05],
       [9.45130885e-02, 4.80121076e-02, 5.66155136e-01, ...,
        1.24664515e-01, 3.08442116e-02, 7.41639733e-03],
       [2.99732983e-02, 2.85172164e-02, 5.38798332e-01, ...,
        1.98304832e-01, 4.41916585e-02, 3.69310379e-03],
       ...,
       [3.56460750e-01, 1.60032362e-01, 4.79491591e-01, ...,
        5.69956601e-02, 8.09014440e-02, 1.61328614e-02],
       [2.47651190e-01, 1.11799508e-01, 3.24926198e-01, ...,
        1.85551941e-02, 1.41535103e-02, 1.55001879e-04],
       [8.35439265e-02, 4.63199914e-02, 4.71906096e-01, ...,
        1.51913941e-01, 5.16614914e-02, 3.49256396e-03]], dtype=float32)

In [5]:
pred_y.shape

(10352, 14)

In [6]:
d=np.load('Y_test.npy')

In [7]:
d.shape

(10352, 14)

In [33]:
labels=np.zeros((10352,14))

In [34]:
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
for i in range(10352):
    if (pred_y[i][0]>0.1):
        labels[i][0]=1   
    

In [36]:
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
for i in range(10352):
    if (pred_y[i][1]>0.1):
        labels[i][1]=1 

In [38]:
labels

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
for i in range(10352):
    if (pred_y[i][2]>0.3):
        labels[i][2]=1 

In [40]:
for i in range(10352):
    if (pred_y[i][3]>0.1):
        labels[i][3]=1 

In [41]:
for i in range(10352):
    if (pred_y[i][4]>0.1):
        labels[i][4]=1 

In [42]:
for i in range(10352):
    if (pred_y[i][5]>0.05):
        labels[i][5]=1 

In [43]:
for i in range(10352):
    if (pred_y[i][6]>0.05):
        labels[i][6]=1 

In [44]:
for i in range(10352):
    if (pred_y[i][7]>0.1):
        labels[i][7]=1 

In [45]:
for i in range(10352):
    if (pred_y[i][8]>0.05):
        labels[i][8]=1 

In [46]:
for i in range(10352):
    if (pred_y[i][9]>0.1):
        labels[i][9]=1 

In [47]:
for i in range(10352):
    if (pred_y[i][10]>0.1):
        labels[i][10]=1 

In [48]:
for i in range(10352):
    if (pred_y[i][11]>0.1):
        labels[i][11]=1 

In [49]:
for i in range(10352):
    if (pred_y[i][12]>0.1):
        labels[i][12]=1 

In [50]:
for i in range(10352):
    if (pred_y[i][13]>0.1):
        labels[i][13]=1 

In [51]:
labels

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [52]:
c1=0
for i in range(10352):
    for j in range(14):
        if labels[i][j]==1:
            c1=c1+1

In [53]:
c1

44400

In [54]:
all_labels = ['Atelectasis', 'Consolidation', 'Infiltration', 'Pneumothorax', 'Edema', 'Emphysema', 'Fibrosis', 'Effusion', 'Pneumonia', 'Pleural_Thickening', 
'Cardiomegaly', 'Nodule', 'Mass', 'Hernia',]

In [55]:
j=0
for label in all_labels:
    s=0
    s1=0
    s2=0
    s3=0
    s4=0

    for i in range(10352):
        if(d[i][j]==1):
            s=s+1
            if(d[i][j]==labels[i][j]and labels[i][j]==1):
                s1=s1+1
            if(d[i][j]==1 and labels[i][j]==0):
                s2=s2+1
    for i in range(10352):        
        if(d[i][j]==0 and labels[i][j]==1):
                s3=s3+1
        if(d[i][j]==labels[i][j] and labels[i][j]==0):
                s4=s4+1
                   
    print("%s : %5d %5d %5d %5d %5d"%(label,s,s1,s2,s3,s4))
    j+=1

Atelectasis :  2320  1951   369  4438  3594
Consolidation :   941   670   271  4097  5314
Infiltration :  3999  3823   176  5552   801
Pneumothorax :  1058   476   582   980  8314
Edema :   494   250   244  1164  8694
Emphysema :   489   131   358   467  9396
Fibrosis :   332   157   175  2002  8018
Effusion :  2671  2407   264  4090  3591
Pneumonia :   280    88   192  1911  8161
Pleural_Thickening :   702   225   477  1181  8469
Cardiomegaly :   510   364   146  1270  8572
Nodule :  1207   751   456  3334  5811
Mass :  1201   645   556  1484  7667
Hernia :    38    16    22   476  9838
