In [1]:
import numpy as np

In [2]:
pred_y=np.load("Predictions_ResNet400.npy")

In [3]:
pred_y.shape

(10352, 14)

In [4]:
d=np.load('Y_test.npy')

In [5]:
labels=np.zeros((10352,14))

In [6]:
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
for i in range(10352):
    if (pred_y[i][0]>0.1):
        labels[i][0]=1

In [8]:
for i in range(10352):
    if (pred_y[i][1]>0.1):
        labels[i][1]=1 

In [9]:
for i in range(10352):
    if (pred_y[i][2]>0.3):
        labels[i][2]=1 

In [10]:
for i in range(10352):
    if (pred_y[i][3]>0.1):
        labels[i][3]=1

In [11]:
for i in range(10352):
    if (pred_y[i][4]>0.1):
        labels[i][4]=1 

In [12]:
for i in range(10352):
    if (pred_y[i][5]>0.05):
        labels[i][5]=1 

In [13]:
for i in range(10352):
    if (pred_y[i][6]>0.05):
        labels[i][6]=1 

In [14]:
for i in range(10352):
    if (pred_y[i][7]>0.1):
        labels[i][7]=1 

In [15]:
for i in range(10352):
    if (pred_y[i][8]>0.05):
        labels[i][8]=1 

In [16]:
for i in range(10352):
    if (pred_y[i][9]>0.1):
        labels[i][9]=1 

In [17]:
for i in range(10352):
    if (pred_y[i][10]>0.1):
        labels[i][10]=1 

In [18]:
for i in range(10352):
    if (pred_y[i][11]>0.1):
        labels[i][11]=1 

In [19]:
for i in range(10352):
    if (pred_y[i][12]>0.1):
        labels[i][12]=1 

In [32]:
for i in range(10352):
    if (pred_y[i][13]>0.1):
        labels[i][13]=1 

In [33]:
labels

array([[0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.]])

In [34]:
c1=0
for i in range(10352):
    for j in range(14):
        if labels[i][j]==1:
            c1=c1+1

In [35]:
c1

51696

In [36]:
all_labels = ['Atelectasis', 'Consolidation', 'Infiltration', 'Pneumothorax', 'Edema', 'Emphysema', 'Fibrosis', 'Effusion', 'Pneumonia', 'Pleural_Thickening', 
'Cardiomegaly', 'Nodule', 'Mass', 'Hernia',]

In [37]:
j=0
for label in all_labels:
    s=0
    s1=0
    s2=0
    s3=0
    s4=0

    for i in range(10352):
        if(d[i][j]==1):
            s=s+1
            if(d[i][j]==labels[i][j]and labels[i][j]==1):
                s1=s1+1
            if(d[i][j]==1 and labels[i][j]==0):
                s2=s2+1
    for i in range(10352):        
        if(d[i][j]==0 and labels[i][j]==1):
                s3=s3+1
        if(d[i][j]==labels[i][j] and labels[i][j]==0):
                s4=s4+1
                   
    print("%s : %5d %5d %5d %5d %5d"%(label,s,s1,s2,s3,s4))
    j+=1

Atelectasis :  2320  1941   379  5375  2657
Consolidation :   941   737   204  4873  4538
Infiltration :  3999  3326   673  4240  2113
Pneumothorax :  1058   783   275  4621  4673
Edema :   494   273   221  1523  8335
Emphysema :   489   248   241  2047  7816
Fibrosis :   332   194   138  2820  7200
Effusion :  2671  2649    22  6929   752
Pneumonia :   280    67   213  1098  8974
Pleural_Thickening :   702   261   441  1858  7792
Cardiomegaly :   510   152   358   279  9563
Nodule :  1207   616   591  2429  6716
Mass :  1201   652   549  1703  7448
Hernia :    38     0    38     2 10312


In [39]:
pred_y[:,13]

array([2.9802322e-07, 1.3779044e-02, 1.0811508e-02, ..., 4.6211481e-04,
       4.5925379e-05, 1.3603687e-02], dtype=float32)